# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch 

jobs:
  should_deploy:
    outputs:
      result: ${{ steps.decide.outputs.deploy_or_not }}
    if: github.ref == 'refs/heads/main' # free idea: only deploy from main branch
    runs-on: ubuntu-latest
    steps:
      - id: decide
        uses: cobot/deploy-window-action@v1
        with: # all optional, see action.yml for default values
          earliest-hour: "9"
          latest-hour: "17"
          latest-weekday: "5"
          time-zone: UTC
          force-deploy-phrase: force deploy
  deploy:
    needs:
      - should_deploy
    runs-on: ubuntu-latest  
    if: needs.should_deploy.outputs.result == 'yes'
    steps:
      - uses: actions/checkout@v2
      - run: deploy.sh # run your deploy script
        shell: bash
  notify_skipped_deployment:
    runs-on: ubuntu-latest
    needs:
      - should_deploy
    if: needs.should_deploy.outputs.result == 'no'
    steps:
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: Ilshidur/action-slack@689ad44a9c9092315abd286d0e3a9a74d31ab78a
        with:
          args: ":warning: Deployment skipped. Now is not a good time. :warning:\nCommit: https://github.com/${{github.repository}}/commit/${{github.sha}}\nRe-run here: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
